first_name= input("Enter your first name  :" )
last_name=input("Enter your last name   :")
Phone_no=input("enter the phone no ")
Address=input("Enter the address :")
Ditrict=input("Enter the district :")
Pin_code= input("Enter the pincode ")
print (f"hello {first_name} {last_name}")
print(f"Your phone no is {Phone_no}")
print(f"Your address is {Address}")
print(f"Your district and pincode is {Ditrict} and{Pin_code}")